### ISSUE TITLE
Only setup.account?getProvisionInfo work via HTTP Post

### ISSUE THREAD

**Issue by jimsmt** [NovaGL/diy-harmonyhub#2]
Only the command `setup.account?getProvisionInfo` work via HTTP Post on my Harmony Hub, while the others only work via websocket, code "417" returned if using HTTP Post method

Hub firmware version 4.15.250

**Comment by NovaGL** [comment]
I am aware of this. The aim is to update this repo and add the websocket  equivalents which still work. I'll update you here when that is done.

**Comment by jimsmt** [comment]
I use tcpdump on my router to capture the websocket traffic between the iOS Harmony App and Harmony hub, I will test more commands when I got time

**Comment by NovaGL** [comment]
Great. I use Charles proxy I find putting  stuff a router level is to complex. 

I find wireshark to difficult to use.

**Comment by jimsmt** [comment]
Does Charles support websocket?

If you have an openwrt router, it's very easy

opkg update
opkg install tcpdump
tcpdump -i wlan0 -w output.file

then open the output.file using wireshark on a PC

**Comment by NovaGL** [comment]
Yes. I have the commands i just never got around to putting them here as http post was working

**Comment by NovaGL** [comment]
I have started to add some websocket commands.

Just done the basics at the moment, will add more when I have a chance.
It's the ones people will use most.

- Getting hub configuration including devices and activities
- Starting an activity
- Issuing a device command

I think this should be sufficient for the time being.
Please advise if you think this issue has been resolved?
