### ISSUE TITLE
response 417 when trying to get configuration

### ISSUE THREAD

**Issue by psybertech** [NovaGL/diy-harmonyhub#4]
Hi there.

Slow to the party...

I just got my hub and was able to get the initial response for the account info using:
`{"id":29549457,"cmd":"setup.account?getProvisionInfo","timeout":90000}`
It returns expected results....

However, I cannot get the API to return using:
```
{
	"hubId": "[MyRemoteID]",
	"timeout": 60,
	"hbus": {
		"cmd": "vnd.logitech.harmony\/vnd.logitech.harmony.engine?config",
		"id": "0",
		"params": {
			"verb": "get"
		}
	}
}
```
All I get is a response of "417 Expectation Failed".

Am I missing anything....

I have tried a few different header  attempts changing the Origin based on other examples I have found out there, but I still can't get a response.

Any help would be appreciated.

Thanks
j

**Comment by NovaGL** [comment]
Logitech has disabled HTTP POST commands.

It now has to be done through websocket.

How are you issuing commands?

I use node-red but any platform that supports websocket should work.
