### ISSUE TITLE
How to control the volume for current Activity

### ISSUE THREAD

**Issue by ogiewon** [NovaGL/diy-harmonyhub#5]
@NovaGL Thank you for this documentation regarding the Harmony Hub webSockets API.  I am trying to determine if there is a way to control the volume (i.e. Mute, VolumeUp, VolumeDown) for the correct device for the current active activity.  

I can start and stop activities.  I can control the volume of a specific device.  I am just not sure how to determine which device is the correct one for the current activity.  Or, is there a way to simply send volume control commands to the Activity, instead of the Device?  Obviously the Harmony Hub know what device is supposed to control the volume for the current activity already.  Seems like there should be a simple way to send volume commands.

Any help you can provide would be very much appreciated.

**Comment by NovaGL** [comment]
Happy to help.

It requires several steps. I'm using Node-red and JSONata but hopefully you can adapt it to your needs.
There might be a better way to do this but this is the way I know at the moment. All commands assume you are already connected via websocket.

First you need to find what the current activity is.

```json
{
	"hubId": "[MyRemoteID]",
	"timeout": 60,
	"hbus": {
		"cmd": "vnd.logitech.harmony\/vnd.logitech.harmony.engine?getCurrentActivity",
		"id": "0",
		"params": {
			"verb": "get"
		}
	}
}
```

Store the result in a variable for use later.

```json
{
  "cmd": "vnd.logitech.harmony\/vnd.logitech.harmony.engine?getCurrentActivity",
  "code": 200,
  "id": "0",
  "msg": "OK",
  "data": {
    "result": "00000000"
  }
}
```

I will use 00000000 for activity id for this example.
Now that we have the activity we want to control we need to know what devices are doing what.

You get this information from running the following websocket command

```json
{
	"hubId": "[MyRemoteID]",
	"timeout": 60,
	"hbus": {
		"cmd": "vnd.logitech.harmony\/vnd.logitech.harmony.engine?config",
		"id": "0",
		"params": {
			"verb": "get"
		}
	}
}
```

You have two ways of filtering the data to get achieve what you want.
If you just want to know what device is controlling what you can get it this way:

Get the deviceId that controls the Volume
```$.data.activity[id='00000000'].roles.VolumeActivityRole```

Get the deviceId that controls the display
```$.data.activity[id='00000000'].roles.DisplayActivityRole```

Get the deviceId that controls channel changing
```$.data.activity[id='00000000'].roles.ChannelChangingActivityRole```

Alternatively, if you want to know what that full commands are you can find it using the following JSONata code.

```
{
  "Volume": $.data.activity[id='00000000'].controlGroup[name='Volume'].function.({
  $.label:$.action  
  })
}
```

The benefit of doing it this way is you get the full command so you don't need to guess what it is.
The result will look similar to this:

```json
{
  "Volume": [
    {
      "Mute": "{\"command\":\"Mute\",\"type\":\"IRCommand\",\"deviceId\":\"99999999\"}"
    },
    {
      "Volume Down": "{\"command\":\"VolumeDown\",\"type\":\"IRCommand\",\"deviceId\":\"99999999\"}"
    },
    {
      "Volume Up": "{\"command\":\"VolumeUp\",\"type\":\"IRCommand\",\"deviceId\":\"99999999\"}"
    }
  ]
}
```

**Comment by ogiewon** [comment]
Excellent!  Thank you very, very much. This is exactly what I needed!  Thank you for taking the time out of your weekend to lend a hand.
